version: '3.1'
services:

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=tr1sch00l!
      - MYSQL_DATABASE=NewsAuth_Network
      - MYSQL_USER=trillian
      - MYSQL_PASSWORD=tr1sch00l!
    volumes:
    - "trillian-data:/var/lib/mysql"
    restart: always

  adminer:
    image: adminer:4.7.1
    restart: always
    ports:
      - 8080:8080    

  trillian-log-server:
    depends_on:
      - db
    image: gcr.io/trillian-opensource-ci/log_server@sha256:73180a17a00470f073948434d3594c181247678cb8003c7e5e22a2095f231e31
    command: [
      "--storage_system=mysql",
      "--mysql_uri=test:zaphod@tcp(db:3306)/test",
      "--rpc_endpoint=0.0.0.0:8090",
      "--http_endpoint=0.0.0.0:8091",
      "--alsologtostderr",
    ]
    restart: always
    ports:
      - "8090:8090"
      - "8091:8091"

  trillian-log-signer:
    image: gcr.io/trillian-opensource-ci/log_signer@sha256:bb3f6f0e11329da904df2850198e4756056986b48036a8a6d0b120d3636e3c5d
    depends_on:
      - db
    command: [
      "--storage_system=mysql",
      "--mysql_uri=test:zaphod@tcp(db:3306)/test",
      "--rpc_endpoint=0.0.0.0:8090",
      "--http_endpoint=0.0.0.0:8091",
      "--force_master",
      "--alsologtostderr",
    ]
    restart: always
    ports:
      - "8092:8091"

volumes:
  trillian-data:
    external: true
